  plt.title("Basin Hopping: 25% Platinum")
  plt.plot(x1,z1,label="Silver")
  plt.plot(x2,z2,label="Gold")
  plt.plot(x3,z3,label="Copper")
  plt.plot(x4,z4,label="Iridium")
  plt.plot(x5,z5,label="Nickel")
  plt.plot(x6,z6,label="Palladium")
  plt.plot(x7,z7,label="Rhodium")
  plt.xlabel('# of Atoms')
  plt.ylabel('PE per Atom')
  #plt.legend()
  plt.show()
  plt.autoscale_view()
